"use client";

import Link from "next/link";
import { CheckCircle2, Key, ShieldCheck, XCircle } from "lucide-react";
import { useApi } from "@/lib/api";
import { count, percent } from "@/lib/format";
import {
  Badge,
  Button,
  Card,
  Note,
  PageHeader,
  SectionHeader,
  Skeleton,
} from "@/components/ui";

type Workspace = {
  name: string;
  source: string;
  hasData: boolean;
  counts: { customers: number; transactions: number; products: number; opportunities: number };
  dataHealth: number | null;
  dataGrade: string;
  pipelineMs: number | null;
  imports: { entity: string; filename: string; rows: number; confidence: number }[];
  config: { aiEnabled: boolean; aiModel: string | null; currency: string; locale: string; minimisePii: boolean };
};

type Methodology = {
  weights: { key: string; label: string; weight: number }[];
  principle: string;
  confidenceLevels: Record<string, string>;
};

export default function SettingsPage() {
  const { data } = useApi<Workspace>("/workspace");
  const { data: method } = useApi<Methodology>("/recommendations/methodology");

  if (!data) return <Skeleton className="h-96 w-full" />;

  return (
    <div className="space-y-5">
      <PageHeader
        eyebrow="Configuration"
        title="Settings"
        subtitle="How this instance is configured, and how the decisions it makes are calculated."
      />

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <SectionHeader eyebrow="Workspace" title={data.name} />
          <dl className="space-y-2.5 text-[12.5px]">
            {[
              ["Data source", data.source === "demo" ? "Demo boutique" : data.source === "upload" ? "Your uploads" : "Empty"],
              ["Customers", count(data.counts.customers)],
              ["Transactions", count(data.counts.transactions)],
              ["Products", count(data.counts.products)],
              ["Opportunities detected", count(data.counts.opportunities)],
              ["Data health", data.dataHealth != null ? `${data.dataHealth}/100 (${data.dataGrade})` : "—"],
              ["Last analysis", data.pipelineMs != null ? `${(data.pipelineMs / 1000).toFixed(1)}s` : "—"],
              ["Currency", data.config.currency],
            ].map(([label, value]) => (
              <div key={label} className="flex items-center justify-between gap-3">
                <dt className="text-[var(--color-ink-3)]">{label}</dt>
                <dd className="num font-medium">{value}</dd>
              </div>
            ))}
          </dl>
        </Card>

        <Card>
          <SectionHeader eyebrow="AI" title="Claude configuration" />
          <div className="flex items-start gap-3 rounded-[10px] border border-[var(--color-line)] px-3.5 py-3">
            {data.config.aiEnabled ? (
              <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--color-positive)]" />
            ) : (
              <XCircle className="mt-0.5 size-4 shrink-0 text-[var(--color-warning)]" />
            )}
            <div>
              <div className="text-[12.5px] font-medium">
                {data.config.aiEnabled ? "Connected" : "Not configured"}
              </div>
              <p className="mt-1 text-[12px] leading-relaxed text-[var(--color-ink-3)]">
                {data.config.aiEnabled ? (
                  <>
                    Narrative answers, briefings and campaign copy are generated by{" "}
                    <span className="font-mono text-[11.5px]">{data.config.aiModel}</span>.
                  </>
                ) : (
                  <>
                    Set <span className="font-mono text-[11.5px]">ANTHROPIC_API_KEY</span> in the
                    backend environment and restart to enable written answers. Every analytical
                    feature works without it — the AI layer narrates, it does not calculate.
                  </>
                )}
              </p>
            </div>
          </div>

          <div className="mt-3 space-y-2">
            <div className="flex items-center gap-2.5 text-[12px] text-[var(--color-ink-3)]">
              <Key className="size-3.5 shrink-0 text-[var(--color-ink-4)]" />
              The key is read server-side only and is never sent to this browser.
            </div>
            <div className="flex items-center gap-2.5 text-[12px] text-[var(--color-ink-3)]">
              <ShieldCheck className="size-3.5 shrink-0 text-[var(--color-ink-4)]" />
              PII minimisation is{" "}
              <Badge size="sm" tone={data.config.minimisePii ? "positive" : "warning"}>
                {data.config.minimisePii ? "on" : "off"}
              </Badge>
            </div>
          </div>
        </Card>
      </div>

      {method ? (
        <Card>
          <SectionHeader
            eyebrow="Transparency"
            title="How the match score is calculated"
            subtitle={method.principle}
          />
          <div className="grid gap-6 md:grid-cols-[1.2fr_1fr]">
            <div className="space-y-2">
              {method.weights.map((weight) => (
                <div key={weight.key} className="flex items-center gap-3">
                  <span className="w-[136px] shrink-0 text-[12px]">{weight.label}</span>
                  <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-[var(--color-surface-2)]">
                    <div
                      className="h-full rounded-full bg-[var(--color-accent)]"
                      style={{ width: `${(weight.weight / 0.22) * 100}%` }}
                    />
                  </div>
                  <span className="num w-9 shrink-0 text-right text-[11.5px] text-[var(--color-ink-4)]">
                    {(weight.weight * 100).toFixed(0)}%
                  </span>
                </div>
              ))}
            </div>
            <div className="space-y-2">
              <div className="eyebrow">Data confidence levels</div>
              {Object.entries(method.confidenceLevels).map(([level, meaning]) => (
                <div key={level} className="text-[11.5px] leading-relaxed">
                  <Badge size="sm">{level}</Badge>{" "}
                  <span className="text-[var(--color-ink-3)]">{meaning}</span>
                </div>
              ))}
            </div>
          </div>
        </Card>
      ) : null}

      <Card>
        <SectionHeader title="Import history" />
        {data.imports.length ? (
          <div className="space-y-1.5">
            {data.imports.map((entry, index) => (
              <div
                key={index}
                className="flex items-center justify-between gap-3 rounded-[9px] border border-[var(--color-line)] px-3 py-2 text-[12.5px]"
              >
                <span className="min-w-0 flex-1 truncate">{entry.filename}</span>
                <Badge size="sm">{entry.entity}</Badge>
                <span className="num shrink-0 text-[var(--color-ink-4)]">
                  {count(entry.rows)} rows
                </span>
                <span className="num w-12 shrink-0 text-right text-[var(--color-ink-4)]">
                  {percent(entry.confidence)}
                </span>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-[12.5px] text-[var(--color-ink-4)]">Nothing imported yet.</p>
        )}
        <div className="mt-4">
          <Link href="/data">
            <Button>Manage data</Button>
          </Link>
        </div>
      </Card>
    </div>
  );
}
